spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: Postgres2018!
  jpa:
    hibernate:
      ddl-auto: update
app:
  write:
    enabled: true

springdoc:
  packagesToScan: com.wsousa.cqrspattern.controller.command, com.wsousa.cqrspattern.controller.query
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


